name: PlayerReviewer
main: me.engineersbox.playerrev.Main
version: 2.6
author: EngineersBox
description: Review Player Rank Applications
commands:
    pr:
        description: Allows The Use Of The pr Command
        usage: /pr
        permission: pr.use
    pr help:
        description: Displays All Help Options For Player Reviewer
        usage: /pr help
        permission: pr.help
    pr apphelp:
        description: Displays application submission help
        usage: /pr apphelp
        permission: pr.apphelp
    pr renderhelp:
        description: Displays render submission help
        usage: /pr renderhelp
        permission: pr.renderhelp
    pr apply:
        description: Allow Player To Apply For Rank Reviewal
        usage: /pr apply [<rank>]
        permission: pr.apply
    pr validranks:
        description: Displays All Valid Ranks
        usage: /pr validranks
        permission: pr.validranks
        aliases: [ranks, vr]
    pr rate:
        description: Allows Player To Rate Open Applications
        usage: /pr rate <player> <criteria 1> <criteria 2> ...
        permission: pr.rate
    pr gotoplot:
        description: Allows Player To Go To Plot Of Open Application
        usage: /pr gotoplot <player>
        permission: pr.gotoplot
        aliases: [plot]
    pr ratings:
        description: Displays Recieved Ratings Of Open Application
        usage: /pr ratings <player>
        permission: pr.ratings
    pr approval:
        description: Allows Player To Approve Or Deny Open Applications
        usage: /pr approval <approve/deny>
        permission: pr.approval
    pr removeapplication:
        description: Allows Player To Remove Open Application
        usage: /pr removeapplication <name>
        permission: pr.removeapplication
        aliases: [remapp, ra]
    pr version:
        description: Allows Player To View Plugin Version Information
        usage: /pr version
        permission: pr.version
    pr status:
        description: Allows Player To View Application Status
        usage: /pr status
        permission: pr.status
    pr submissions:
        description: Allows Player To View A List Build Submissions
        usage: /pr submissions
        permission: pr.submissions
    pr removesubmission:
        description: Allows Player To Remove A Specific Submission
        usage: /pr removesubmission
        permission: pr.removesubmission
        aliases: [rs, remsub]
    pr pos1:
        description: Register position 1
        usage: /pr pos1
        permission: pr.pos1
    pr pos2:
        description: Register position 2
        usage: /pr pos2
        permission: pr.pos2
    pr cam:
        description: Register a camera
        usage: /pr cam
        permission: pr.cam
    pr chunkysettings:
        description: Returns position, chunk and parameter details
        usage: /pr chunkySettings
        permission: pr.chunkysettings
        aliases: [cs]
    pr setparam:
        description: Set a chunky JSON parameter
        usage: /pr setparam <json paramters>
        permission: pr.setparam
        aliases: [sp]
    pr removeparam:
        description: Remove a chunky JSON parameter
        usage: /pr removeparam <parameter name>
        permission: pr.removeparam
        aliases: [rp]
    pr viewparams:
        description: View currently set chunky JSON parameters
        usage: /pr viewparams <raw/list>
        permission: pr.viewparams
        aliases: [vp]
    pr clearparams:
        description: Clear all currently set chunky JSON parameters (requires confirmation)
        usage: /pr clearparams [<confirm/deny>]
        permission: pr.clearparams
        aliases: [cp]
permissions:
    pr.*:
        description: Gives Access To All Player Reviewer Commands
        children:
            pr.use: true
            pr.help: true
            pr.apphelp: true
            pr.renderhelp: true
            pr.apply: true
            pr.validranks: true
            pr.rate: true
            pr.gotoplot: true
            pr.ratings: true
            pr.approval: true
            pr.removeapplication: true
            pr.version: true
            pr.status: true
            pr.submissions: true
            pr.removesubmission: true
            pr.pos1: true
            pr.pos2: true
            pr.cam: true
            pr.chunkysettings: true
            pr.setparam: true
            pr.removeparam: true
            pr.viewparams: true
            pr.clearparams: true
            pr.list: true
            pr.raw: true
    pr.use:
        description: Allows The Use Of The pr Command
        default: true
    pr.help:
        description: Displays All Help Options For Player Reviewer
        default: true
    pr.apply:
        description: Allow Player To Apply For Rank Reviewal
        default: true
    pr.apphelp:
        description: Allows the use of /pr apphelp
        default: true
    pr.renderhelp:
        description: Allows the use of /pr renderhelp
        default: true
    pr.validranks:
        description: Displays All Valid Ranks
        default: true
    pr.rate:
        description: Allows Player To Rate Open Applications
        default: op
    pr gotoplot:
        description: Allows Player To Go To Plot Of Open Application
        default: op
    pr.ratings:
        description: Displays Recieved Ratings Of Open Application
        default: op
    pr.approval:
        description: Allows Player To Approve Or Deny Open Applications
        default: op
    pr.removeapplication:
        description: Allows Player To Remove Open Application
        default: true
    pr.version:
        description: Allows Player To View Plugin Version Information
        default: true
    pr.status:
        description: Allows the use of /pr status
        default: true
    pr.submissions:
        description: Allows the use of /pr submissions
        default: true
    pr.removesubmission:
        description: Allows the use of /pr removesubmission
        default: true
    pr.pos1:
        description: Allows the use of /pr pos1
        default: true
    pr.pos2:
        description: Allows the use of /pr pos2
        default: true
    pr.cam:
        description: Allows the use of /pr cam
        default: true
    pr.chunkysettings:
        description: Allows the use of /pr chunkysettings
        default: true
    pr.setparam:
        description: Allows the use of /pr setparam
        default: true
    pr.removeparam:
        description: Allows the use of /pr removeparam
        default: true
    pr.viewparams:
        description: Allows the use of /pr viewparams
        default: true
    pr.clearparams:
        description: Allows the use of /pr clearparams
        default: true
    pr.raw:
        description: Allows viewing parameters in raw JSON format
        default: true
    pr.list:
        description: Allows viewing parameters in list format
        default: op