name: PlayerReviewer
main: me.engineersbox.playerrev.Main
version: 2.5
author: EngineersBox
description: Review Player Rank Applications
commands:
    pr:
        description: Allows The Use Of The pr Command
        usage: /pr
        permission: pr.use
    pr help:
        description: Displays All Help Options For Player Reviewer
        usage: /pr help
        permission: pr.help
    pr apply:
        description: Allow Player To Apply For Rank Reviewal
        usage: /pr apply <rank>
        permission: pr.apply
    pr validranks:
        description: Displays All Valid Ranks
        usage: /pr validranks
        permission: pr.validranks
        aliases: [ranks, vr]
    pr rate:
        description: Allows Player To Rate Open Applications
        usage: /pr rate <player> <criteria 1> <criteria 2> ...
        permission: pr.rate
    pr gotoplot:
        description: Allows Player To Go To Plot Of Open Application
        usage: /pr gotoplot <player>
        permission: pr.gotoplot
        aliases: [plot]
    pr ratings:
        description: Displays Recieved Ratings Of Open Application
        usage: /pr ratings <player>
        permission: pr.ratings
    pr approval:
        description: Allows Player To Approve Or Deny Open Applications
        usage: /pr approval <approve/deny>
        permission: pr.approval
    pr removeapplication:
        description: Allows Player To Remove Open Application
        usage: /pr removeapplication <name>
        permission: pr.removeapplication
        aliases: [remapp, ra]
    pr version:
        description: Allows Player To View Plugin Version Information
        usage: /pr version
        permission: pr.version
    pr pos1:
        description: Register position 1
        usage: /pr pos1
        permission: pr.pos1
    pr pos2:
        description: Register position 2
        usage: /pr pos2
        permission: pr.pos2
    pr cam:
        description: Register a camera
        usage: /pr cam
        permission: pr.cam
    pr get:
        description: Returns position and chunk details
        usage: /pr get
        permission: pr.get
    rs:
        description: Returns position and chunk details
        usage: /rs
        permission: rs.use
    rs setparam:
        description: Returns position and chunk details
        usage: /rs setparam <parameter> <value>
        permission: rs.setparam
        aliases: [sp]
    rs viewparams:
        description: Returns position and chunk details
        usage: /rs viewparams <raw/list>
        permission: rs.viewparams
        aliases: [vp]
    rs clearparams:
        description: Returns position and chunk details
        usage: /rs clearparams [<confirm/deny>]
        permission: rs.clearparams
        aliases: [cp]
permissions:
    pr.*:
        description: Gives Access To All Player Reviewer Commands
        children:
            pr.use: true
            pr.help: true
            pr.apply: true
            pr.validranks: true
            pr.rate: true
            pr.gotoplot: true
            pr.ratings: true
            pr.approval: true
            pr.removeapplication: true
            pr.version: true
            pr.pos1: true
            pr.pos2: true
            pr.cam: true
            pr.get: true
            rs.use: true
            rs.setparam: true
            rs.viewparams: true
            rs.clearparams: true
            rs.list: true
            rs.raw: true
    pr.use:
        description: Allows The Use Of The pr Command
        default: true
    pr.help:
        description: Displays All Help Options For Player Reviewer
        default: true
    pr.apply:
        description: Allow Player To Apply For Rank Reviewal
        default: true
    pr.validranks:
        description: Displays All Valid Ranks
        default: true
    pr.rate:
        description: Allows Player To Rate Open Applications
        default: op
    pr gotoplot:
        description: Allows Player To Go To Plot Of Open Application
        default: op
    pr.ratings:
        description: Displays Recieved Ratings Of Open Application
        default: op
    pr.approval:
        description: Allows Player To Approve Or Deny Open Applications
        default: op
    pr.removeapplication:
        description: Allows Player To Remove Open Application
        default: true
    pr.version:
        description: Allows Player To View Plugin Version Information
        default: true
    pr.pos1:
        description: Allows the use of /pr pos1
        default: true
    pr.pos2:
        description: Allows the use of /pr pos2
        default: true
    pr.cam:
        description: Allows the use of /pr cam
        default: true
    pr.get:
        description: Allows the use of /pr get
        default: true
    rs.use:
        description: Allows the use of /rs
        default: true
    rs.setparam:
        description: Allows the use of /rs setparam
        default: true
    rs.viewparams:
        description: Allows the use of /rs viewparams
        default: true
    rs.clearparams:
        description: Allows the use of /rs clearparams
        default: true
    rs.raw:
        description: Allows viewing parameters in raw JSON format
        default: true
    rs.list:
        description: Allows viewing parameters in list format
        default: op